### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by muttering-oldman** [fragaria/address-formatter#273]
Hi guys!
First I want to say thank you for your work!
It is very good that it is possible to support the usual address formats for each country.
Is TypeScript support planned?
Are there any plans to create `@types/fragaria__address-formatter` ?

**Comment by JirkaChadima** [comment]
Hi, I'm sorry I missed this issue. Unfortunately, I don't plan to support this anytime soon. Feel free to send a PR with it. I don't think the interface will change a lot in the future, so it should be quite stable.

**Comment by JirkaChadima** [comment]
@muttering-oldman How about this? https://github.com/fragaria/address-formatter/blob/master/index.d.ts

Does this work?
