### ISSUE TITLE
Default country field

### ISSUE THREAD

**Issue by atomcorp** [fragaria/address-formatter#32]
Hey thanks for putting together!

I've run into an issue with supplying invalid or unsupported country codes. Was wondering whether you felt it was outside the remit of this module, or something that could be supported. 

Currently if I supply an invalid or unsupported country code, there's a type error which crashes everything. The work around I used was to use the private methods of address-formatter to validate the country code, and default to something that works if not. [Here's a codepen example to demonstrate the problem and fix, for you or any other curious folk](https://codepen.io/atomcorp/pen/BaaYYQp).

I'd propose there should be a defaultCountryCode field in the options, which the module can fallback on if an invalid country code is supplied.

I had a look at the source, and it didn't look super simple to fix, but if you're keen to address (heh) this and don't have time, I can take a stab.

**Comment by JirkaChadima** [comment]
Hi, this is actually not that hard if I understand your problem correctly.

I've fixed the crash and it's now falling back to the default formatter. So I guess that's better.

It is possible to *overwrite* the incoming `country_code` by supplying the `countryCode` manually in the options argument. But that's not a fallback.

So I've added the fallback anyway...

Check out the 2.1.0 release (it should show up on npm any minute), I hope it does what you need it to. Thanks for bringing this up!

If I understood the issue poorly, please reopen.

**Comment by atomcorp** [comment]
Works great, thanks for implementing!
