### ISSUE TITLE
House number not recognized from Photon API response

### ISSUE THREAD

**Issue by JakobMiksch** [fragaria/address-formatter#493]
This package only accepts house numbers if the property is spelled in one of this ways:
- `houseNumber` (CamelCase)
- `house_number` (snake_case)

The spelling `housenumber` (all lower case) is not supported, but unfortunately this is how the Photon GeoCoding API responds ([example request](https://photon.komoot.io/api/?q=Poststrasse%2044,%20Heidelberg)).

I can try to provide a fix. 

Am I correct that [normalizeComponentKeys ](https://github.com/fragaria/address-formatter/blob/c34b3250b4b4d77d4ea3972bd66ba553a3a1bce6/src/index.js#L68-L80) is the right function to change?

**Comment by JirkaChadima** [comment]
Hello, good catch. The correct cause of action is a PR against the datasource for this library - you need to add `housenumber` as alias here https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml#L4

Once that is merged, I will bump my library. I don't want to introduce any hard-coded mapping of keys/values in the JS code.

**Comment by JakobMiksch** [comment]
Thanks for the hint. What I do not understand: `houseNumber` is accepted in this library, but is not mentioned as alias in the conf. 
What is the difference in this case?

**Comment by JirkaChadima** [comment]
The capital letter N - this allows automatical replacement for `house_number`. Without the capital N, there is no lead on where to put the underscore to match the original format `house_number` algorithmicaly. The camelCase works for all fields, not only for houseNumber.

**Comment by JakobMiksch** [comment]
I added a PR in the this repo: https://github.com/OpenCageData/address-formatting/pull/81

**Comment by tomdavidson** [comment]
Can we run our own [conf/components.yaml](https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml) with address-formatter?

**Comment by JirkaChadima** [comment]
@tomdavidson Yes, but you'd need to make your own build. The link to the conf/components is in the `prepare-templates` script here https://github.com/fragaria/address-formatter/blob/master/management/prepare-templates.js#L52

The products of that script are JSON files which are then bundled with the built code.
