### ISSUE TITLE
data loss and out of order results

### ISSUE THREAD

**Issue by tomdavidson** [fragaria/address-formatter#568]
Hello I'm trying to put address-formatter (v2.8.0) to work, but am getting incomplete results.

```js

addressformatter.format(
  {
    houseNumber: "100",
    road: "oceanside drive",
    city: "nashville",
    state: "tn",
    postcode: "37204",
    house: "24/7 financial advance",
  },
  {
    abbreviate: true,
    fallbackCountryCode: "USA",
    cleanupPostcode: true,
    output: "array",
  }
);

```

yields:
```json
[
  "24/7 financial advance",
  "oceanside drive 100",
  "37204 nashville"
]
```

where I expected:
```json
[
  "24/7 financial advance",
  "100 oceanside drive",
  "nashville, tn 37204"
]
```

Am I using it incorrectly or have incorrect expectations?

**Comment by JirkaChadima** [comment]
@tomdavidson use `fallbackCountryCode` `US`, not `USA` and you'll get what you are expecting

**Comment by tomdavidson** [comment]
@JirkaChadima  thanks for the quick response. 

Any advice on the ordering? It seems to only be the po boxes that end up on the first line when it shouldnt.

```
[
  "po box 3115",
   "kohl's department store",
  "milwaukee, wi 53201"
]
```

**Comment by JirkaChadima** [comment]
I don't think the JS code is doing any ordering. The output is entirely based on the templates defined in https://github.com/OpenCageData/address-formatting so I don't know - I'm not an expert on the templates
