### ISSUE TITLE
README.md does not work with version 3.0.1

### ISSUE THREAD

**Issue by giggls** [fragaria/address-formatter#653]
Format function seems to be renamed from `myinstance.format()` to `myinstance.default.format()`

Correct?

**Comment by JirkaChadima** [comment]
@giggls Can you try to draft a PR with the README update? This might have changed with some changes in the build/release process.

**Comment by giggls** [comment]
It seems to works for me by replacing ``addressFormatter.format`` with ``addressFormatter.default.format`` but I do not know about the rationale behind this.

**Comment by JirkaChadima** [comment]
@giggls FYI in version 5.0.0 the default exports are back thanks to @chrisweb . You can skip the release 4 which broke this
