### ISSUE TITLE
when napa is used, the package cannot be installed from npm

### ISSUE THREAD

**Issue by JirkaChadima** [fragaria/address-formatter#7]
Because napa is declared as a dev dependency (which it is), it is not installed when getting this from npm. But, npm is running `install` script which tries to run napa and that fails.

**Comment by millette** [comment]
That was reverted a few days later, the current version 2.0.5 released at npm doesn't use napa.

**Comment by JirkaChadima** [comment]
@millette I know, I did that revert ;) I'd like to use napa instead of a git submodule to reference the original repo, so this issue here is just a reminder.

**Comment by millette** [comment]
I didn't pay close enough attention, I apologize for the noise, @JirkaChadima

**Comment by JirkaChadima** [comment]
Closing, looks like it works well with git submodules. No need to depend on napa.
