### ISSUE TITLE
Issues with Canadian addresses?

### ISSUE THREAD

**Issue by itamok** [fragaria/address-formatter#844]
```
console.log(addressFormatter.format({
    city: "Montréal",
    country: "Canada",
    postcode: "H3A 2W5",
    province: "Quebec",
    streetName: "Rue Peel",
    streetNumber: "2000",
}, { output: 'array' }).toString().replaceAll(",", ", ").trim())
```

Any idea why the above returns:

> Rue Peel 2000, 
> H3A 2W5 Montréal, 
> Canada

Instead of:

> 2000 Rue Peel,
> Montréal, 
> QC H3A 2W5,
> Canada

**Comment by JirkaChadima** [comment]
hi, not really. As the readme says, the formatting rules are defined in https://github.com/OpenCageData/address-formatting/

And this sounds like a test case that should be added there if the expected output is not matching the actual output
